---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/deno --version
    register: deno_test_output
  - name: deno --version
    debug:
      msg: '{{ deno_test_output.stdout }}'
