---
- name: Testing andrewrothstein.deno
  hosts: all
  tasks:
    - name: Installing andrewrothstein.deno
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'deno --version'
      ansible.builtin.command: /usr/local/bin/deno --version
      changed_when: false
      register: deno_test_output
    - name: Output of 'deno --version'
      ansible.builtin.debug:
        msg: '{{ deno_test_output.stdout }}'
