---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Looking for install in {{ deno_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ deno_install_dir }}'
  changed_when: false
  register: deno_binary
- name: Downloading and installing deno
  when: not deno_binary.stat.exists
  block:
    - name: Downloading {{ deno_url }} to {{ deno_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ deno_url }}'
        dest: '{{ deno_tmp_archive }}'
        mode: '644'
        checksum: '{{ deno_checksum }}'
    - name: Mkdir {{ deno_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ deno_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchiving {{ deno_tmp_archive }} into {{ deno_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ deno_tmp_archive }}'
        dest: '{{ deno_install_dir }}'
        creates: '{{ deno_install_exe }}'
  always:
    - name: Rm {{ deno_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ deno_tmp_archive }}'
        state: absent
- name: Linking {{ deno_link }} to {{ deno_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ deno_install_exe }}'
    dest: '{{  deno_link }}'
    state: link
